name: "gdelt_sea"
version: "1.0.0"
config-version: 2

profile: "gdelt_sea"

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  gdelt_sea:
    staging:
      +schema: staging
      +materialized: view
